# Compatibility adaptation of vcpkg 9e593bb18ea69cc5095e012465dcd675a822ed0d
# scripts/cmake/z_vcpkg_spdx.cmake (Microsoft, MIT license).
# Preserve SPDX resource metadata without requiring CMake 4.x STRING_ENCODE.
function(uxas_json_encode out value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    foreach(code RANGE 1 31)
        string(ASCII ${code} character)
        math(EXPR hex "${code}" OUTPUT_FORMAT HEXADECIMAL)
        string(SUBSTRING "${hex}" 2 -1 hex)
        string(LENGTH "${hex}" length)
        if(length EQUAL 1)
            set(hex "0${hex}")
        endif()
        string(REPLACE "${character}" "\\u00${hex}" value "${value}")
    endforeach()
    set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(z_vcpkg_add_spdx_resource)
    cmake_parse_arguments(PARSE_ARGV 0 arg "" "NAME;DOWNLOAD_LOCATION;SHA512;FILENAME" "")
    if(DEFINED arg_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unexpected SPDX resource arguments: ${arg_UNPARSED_ARGUMENTS}")
    endif()
    get_property(Z_VCPKG_SPDX_OBJECTS GLOBAL PROPERTY Z_VCPKG_SPDX_OBJECTS)
    list(LENGTH Z_VCPKG_SPDX_OBJECTS resource_index)
    set(resource "{}")
    string(JSON resource SET "${resource}" SPDXID "\"SPDXRef-resource-${resource_index}\"")
    uxas_json_encode(value "${arg_NAME}")
    string(JSON resource SET "${resource}" name "${value}")
    if(DEFINED arg_FILENAME)
        uxas_json_encode(value "${arg_FILENAME}")
        string(JSON resource SET "${resource}" packageFileName "${value}")
    endif()
    uxas_json_encode(value "${arg_DOWNLOAD_LOCATION}")
    string(JSON resource SET "${resource}" downloadLocation "${value}")
    foreach(property IN ITEMS licenseConcluded licenseDeclared copyrightText)
        string(JSON resource SET "${resource}" "${property}" [["NOASSERTION"]])
    endforeach()
    if(DEFINED arg_SHA512 AND NOT "${arg_SHA512}" STREQUAL "")
        string(TOLOWER "${arg_SHA512}" sha512)
        string(JSON checksum SET "{}" algorithm [["SHA512"]])
        string(JSON checksum SET "${checksum}" checksumValue "\"${sha512}\"")
        string(JSON checksums SET "[]" 0 "${checksum}")
        string(JSON resource SET "${resource}" checksums "${checksums}")
    endif()
    vcpkg_list(APPEND Z_VCPKG_SPDX_OBJECTS "${resource}")
    set_property(GLOBAL PROPERTY Z_VCPKG_SPDX_OBJECTS "${Z_VCPKG_SPDX_OBJECTS}")
endfunction()
