"""Immutable workspace-qualified gateway candidates and receipt-bound publication."""
from datetime import datetime
import hashlib
import importlib.util
import json
from pathlib import Path
import shutil


ROOT = Path(__file__).resolve().parents[2]


def load(path): return json.loads(path.read_text(encoding='utf-8-sig'))
def sha(path):
    with path.open('rb') as stream: return hashlib.file_digest(stream, 'sha256').hexdigest()
def save(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + '.new')
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    temporary.replace(path)
def need(condition, message):
    if not condition: raise RuntimeError(message)
def module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    value = importlib.util.module_from_spec(spec); spec.loader.exec_module(value); return value
def files(root, paths): return [{'path':p.relative_to(root).as_posix(), 'sha256':sha(p)} for p in sorted(paths)]
def verify_files(root, records):
    for row in records:
        path = (root/row['path']).resolve()
        need(path.is_relative_to(root.resolve()) and sha(path)==row['sha256'].lower(), 'File differs: '+row['path'])


def predecessor(root):
    policy = load(root/'config/g4-stage.json')
    for key in ('capture', 'audit'):
        path = root/'out/runs'/policy[key+'RunId']/'result.json'
        need(sha(path)==policy[key+'SHA256'] and load(path)['status']=='passed', 'T08 '+key+' differs')
    capture = load(root/'out/runs'/policy['captureRunId']/'result.json')
    audit = load(root/'out/runs'/policy['auditRunId']/'result.json')
    need(audit['parentResultSHA256']==policy['captureSHA256'] and audit['stabilityValidated'], 'T08 audit unbound')
    auditor = module('stage_scale_provenance', root/'scripts/g4_scale/audit.py')
    auditor.capture_sources(root, capture)
    verify_files(root, audit['auditSources'])
    return policy


def build(root, baseline):
    policy = predecessor(root)
    environment = module('stage_environment', root/'scripts/g4_environment/manage.py')
    provenance = environment.verify_handoff(root, baseline)
    python, _ = environment.environment(root)
    build_id = 'g4-t09-build-'+datetime.now().strftime('%Y%m%d-%H%M%S-%f')
    directory = root/'out/build/gis-gateway'/build_id/'candidate'; directory.mkdir(parents=True)
    source = [p for name in ('src/sim_bridge','apps/gis_gateway') for p in (root/name).rglob('*') if p.is_file()]
    source += [root/'scripts/g4_stage/launch.py']
    for path in source:
        target = directory/path.relative_to(root); target.parent.mkdir(parents=True, exist_ok=True); shutil.copy2(path,target)
    environment_pointer = load(root/'.tools/g4/current.json')
    dependencies = [root/'config/g4-gateway.json', root/'config/g4-baseline.json', root/'scripts/g4_environment/manage.py',
                    root/'config/g4-python-lock.json', root/'config/g4-requirements.txt', root/'.tools/g4/current.json',
                    root/environment_pointer['path']/'environment.json']
    # Include all generated bytes, including model provenance, rather than trusting a directory name.
    dependencies += [p for p in (root/'out/generated/lmcp/py').rglob('*') if p.is_file()]
    dependencies += [root/'out/generated/lmcp/generation-info.json']
    manifest = dict(schemaVersion=1, buildRunId=build_id, baselineRunId=baseline,
        stageQualified=False, packageFiles=files(root,source), workspaceFiles=files(root,dependencies),
        pythonExecutable=str(python), provenance=provenance, stability=policy)
    save(directory/'package.json',manifest)
    return directory


def verify(directory, root, digest=None):
    if digest: need(sha(directory/'package.json')==digest, 'Package manifest changed')
    manifest = load(directory/'package.json')
    verify_files(directory,manifest['packageFiles']); verify_files(root,manifest['workspaceFiles'])
    actual = {p.relative_to(directory).as_posix() for p in directory.rglob('*') if p.is_file()}
    need(actual=={'package.json'}|{r['path'] for r in manifest['packageFiles']}, 'Unexpected package contents')
    return manifest
