include("${CMAKE_CURRENT_LIST_DIR}/../../config/vcpkg/cmake/spdx-cmake331.cmake")
set(sample "quotes=\" backslash=\\ semicolon=; path=中文 空格")
foreach(code RANGE 1 31)
    string(ASCII ${code} character)
    string(APPEND sample "${character}")
endforeach()
uxas_json_encode(encoded "${sample}")
string(JSON document SET "{}" sample "${encoded}")
string(JSON decoded GET "${document}" sample)
if(NOT decoded STREQUAL sample)
    message(FATAL_ERROR "SPDX JSON escaping changed a value")
endif()
message(STATUS "SPDX JSON UTF-8/control character roundtrip passed")
