import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const directory=resolve(process.argv[2]);
const {StateStore}=await import(pathToFileURL(resolve(directory,'store.js')));
const {defaults,health}=await import(pathToFileURL(resolve(directory,'protocol.js')));
const {ReadOnlyConnection}=await import(pathToFileURL(resolve(directory,'connection.js')));
const names=[];function test(name,fn){fn();names.push(name);}
const id='18446744073709551615',sequence='9007199254740993000';
const clock={simulation_time_ms:'1000',start_time_ms:'0',state:1,real_time_multiple:1};
const entity=time=>({entity_id:id,simulation_time_ms:time,position:{latitude_deg:45.3,longitude_deg:-121,altitude_m:1090,altitude_reference:0},attitude:{heading_deg:90,pitch_deg:0,roll_deg:0}});
const snapshot=()=>({schema_version:1,kind:'snapshot',run_id:'run/a',stream_id:'stream',sequence,source_time_ms:clock.simulation_time_ms,state:{entities:{[id]:entity('1000')},tasks:{'7':{task_id:'7',backend_completed:false}},commands:{},routes:{[id]:{planned_mission:{Waypoints:[1,2,3]}}},zones:{},simulation:{...clock}}});
const delta=(changes,seq=BigInt(sequence)+1n)=>({schema_version:1,kind:'delta',run_id:'run/a',stream_id:'stream',sequence:String(seq),source_time_ms:clock.simulation_time_ms,changes});
const up=(collection,id,value)=>({collection,id,op:'upsert',value});
function reject(name,change,initial=true){test(name,()=>{const store=new StateStore();if(initial)store.accept(snapshot());assert.throws(()=>store.accept(change()));assert.equal(store.identity,null);assert.equal(store.samples.size,0);assert.equal(Object.keys(store.state.entities).length,0);});}
test('bigint-exact-and-original-values',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('entities',id,entity('1001'))]));assert.equal(s.identity.sequence,'9007199254740993001');assert.equal(s.state.entities[id].entity_id,id);});
test('replace-entire-object-not-merge',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('entities',id,{entity_id:id})]));assert.deepEqual(s.state.entities[id],{entity_id:id});});
test('completion-keeps-entity-and-plan',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('tasks','7',{task_id:'7',backend_completed:true,completed_time_ms:'1001',completed_entity_ids:[id]})]));assert.ok(s.state.entities[id]);assert.equal(s.state.routes[id].planned_mission.Waypoints.length,3);});
test('delete-removes-samples',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('entities',id,entity('1001'))]));s.accept(delta([{collection:'entities',id,op:'delete'}],BigInt(sequence)+2n));assert.equal(s.samples.size,0);assert.equal(s.state.entities[id],undefined);});
test('fresh-connection-clears-old-run-and-samples',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('entities',id,entity('1001'))]));s.clear();const next=snapshot();next.run_id='another';next.stream_id='new';next.sequence='0';s.accept(next);assert.equal(s.samples.size,0);assert.equal(s.identity.run_id,'another');});
reject('delta-before-snapshot',()=>delta([up('tasks','7',{})]),false);
reject('unknown-version',()=>({...snapshot(),schema_version:2}),false);
reject('duplicate-snapshot',snapshot);
reject('missing-snapshot-collection',()=>{const s=snapshot();delete s.state.zones;return s;},false);
reject('duplicate-delta',()=>delta([up('tasks','7',{})],BigInt(sequence)));
reject('out-of-order',()=>delta([up('tasks','7',{})],BigInt(sequence)-1n));
reject('sequence-gap',()=>delta([up('tasks','7',{})],BigInt(sequence)+2n));
reject('old-stream',()=>({...delta([up('tasks','7',{})]),stream_id:'old'}));
reject('cross-run',()=>({...delta([up('tasks','7',{})]),run_id:'old'}));
reject('numeric-id',()=>delta([up('entities',id,{entity_id:123})]));
reject('unsafe-nested-id',()=>delta([up('tasks','7',{definition:{ID:9007199254740992}})]));
reject('numeric-time',()=>delta([up('simulation','clock',{...clock,simulation_time_ms:1000})]));
reject('time-regression',()=>delta([up('simulation','clock',{...clock,simulation_time_ms:'1'})]));
reject('bad-collection-atomic',()=>delta([up('tasks','7',{done:true}),up('unknown','9',{})]));
reject('bad-operation',()=>delta([{collection:'tasks',id:'7',op:'merge',value:{}}]));
reject('prototype-key',()=>JSON.parse(JSON.stringify(delta([up('tasks','7',{})])).replace('"value":{}','"value":{"__proto__":{}}')));
test('object-limit',()=>{const s=new StateStore({...defaults,objectsPerCollection:1});s.accept(snapshot());assert.throws(()=>s.accept(delta([up('entities','2',{})])));});
test('byte-limit',()=>assert.throws(()=>new StateStore({...defaults,stateBytes:100}).accept(snapshot())));
test('sample-count-and-window-bounds',()=>{const s=new StateStore({...defaults,samplesPerEntity:3,trajectoryWindowMs:'10'});s.accept(snapshot());for(let i=1;i<=8;i++)s.accept(delta([up('entities',id,entity(String(1000+i)))],BigInt(sequence)+BigInt(i)));assert.equal(s.samples.get(id).length,3);s.accept(delta([up('entities',id,entity('2000'))],BigInt(sequence)+9n));assert.equal(s.samples.get(id).length,1);});
test('paused-clock-is-not-extrapolated',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('simulation','clock',{...clock,state:2})]));assert.deepEqual(s.state.simulation,{...clock,state:2});});
test('large-time-remains-exact',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('simulation','clock',{...clock,simulation_time_ms:'9007199254740993001'})]));assert.equal(s.state.simulation.simulation_time_ms,'9007199254740993001');});
test('silent-entity-history-expires-by-backend-time',()=>{const s=new StateStore();s.accept(snapshot());s.accept(delta([up('entities',id,entity('1001'))]));s.accept(delta([up('simulation','clock',{...clock,simulation_time_ms:'700000'})],BigInt(sequence)+2n));assert.equal(s.samples.size,0);});
test('health-before-snapshot-is-not-state',()=>assert.throws(()=>new StateStore().accept({...snapshot(),kind:'health'})));
const goodHealth={schema_version:1,kind:'health',run_id:'run/a',stream_id:'stream',sequence,source_time_ms:clock.simulation_time_ms,status:'live',ready:true,freshness:{paused:false,stale:false},connections:{amase:{connected:true},uxas:{connected:true}}};
test('health-validation',()=>{assert.equal(health(goodHealth).ready,true);assert.throws(()=>health({...goodHealth,schema_version:2}));});
const sockets=[];let httpStatus=200,httpValue=goodHealth;
globalThis.fetch=async()=>({ok:httpStatus===200,status:httpStatus,text:async()=>JSON.stringify(httpValue)});
globalThis.WebSocket=class {constructor(){sockets.push(this);}close(){}send(){throw Error('Browser must not send');}};
const delay=ms=>new Promise(done=>setTimeout(done,ms));
let client=new ReadOnlyConnection('http://127.0.0.1:8080',defaults,()=>{});client.start();await delay(5);
sockets.at(-1).onopen();sockets.at(-1).onmessage({data:JSON.stringify(snapshot())});assert.equal(client.phase,'live');
sockets.at(-1).onclose({code:1013});assert.equal(client.store.identity,null);assert.equal(client.closeCode,1013);assert.equal(client.phase,'recovering');client.stop();names.push('1013-clears-live-state');
httpStatus=503;client=new ReadOnlyConnection('http://127.0.0.1:8080',defaults,()=>{});client.start();await delay(5);assert.equal(client.store.identity,null);assert.equal(client.phase,'recovering');client.stop();names.push('503-not-ready');
httpStatus=200;httpValue={...goodHealth,status:'recovering',ready:false};client=new ReadOnlyConnection('http://127.0.0.1:8080',defaults,()=>{});client.start();await delay(5);sockets.at(-1).onmessage({data:JSON.stringify(httpValue)});assert.notEqual(client.phase,'live');client.stop();names.push('health-only-not-live');
writeFileSync(process.argv[3],JSON.stringify({status:'passed',cases:names,count:names.length,syntheticOnly:true},null,2));
console.log('Reducer and connection checks passed: '+names.length);
