# Select sources from the G1 inventory, never from an unchecked source glob.
file(READ "${UXAS_LMCP_PROVENANCE}" _lmcp_info)
string(JSON _lmcp_count LENGTH "${_lmcp_info}" files)
math(EXPR _lmcp_last "${_lmcp_count} - 1")
set(_lmcp_sources)
set(_lmcp_inventory)
foreach(_i RANGE ${_lmcp_last})
    string(JSON _path GET "${_lmcp_info}" files ${_i} path)
    if(NOT _path MATCHES "^cpp/")
        continue()
    endif()
    string(REGEX REPLACE "^cpp/" "" _relative "${_path}")
    if(_relative MATCHES "(^|/)\\.\\.(/|$)" OR IS_ABSOLUTE "${_relative}")
        message(FATAL_ERROR "Unsafe generated path: ${_path}")
    endif()
    string(JSON _expected GET "${_lmcp_info}" files ${_i} sha256)
    if(NOT EXISTS "${UXAS_LMCP_GENERATED_DIR}/${_relative}")
        message(FATAL_ERROR "Missing generated input: ${_relative}")
    endif()
    file(SHA256 "${UXAS_LMCP_GENERATED_DIR}/${_relative}" _actual)
    string(TOUPPER "${_actual}" _actual)
    if(NOT _actual STREQUAL _expected)
        message(FATAL_ERROR "Generated input hash mismatch: ${_relative}; run generate-lmcp.ps1")
    endif()
    list(APPEND _lmcp_inventory "${_relative}")
    if(_relative MATCHES "\\.cpp$" AND NOT _relative MATCHES "^test/")
        list(APPEND _lmcp_sources "${UXAS_LMCP_GENERATED_DIR}/${_relative}")
    endif()
endforeach()
file(GLOB_RECURSE _lmcp_actual LIST_DIRECTORIES false RELATIVE "${UXAS_LMCP_GENERATED_DIR}" "${UXAS_LMCP_GENERATED_DIR}/*")
list(SORT _lmcp_actual)
list(SORT _lmcp_inventory)
if(NOT _lmcp_actual STREQUAL _lmcp_inventory)
    message(FATAL_ERROR "Generated file inventory differs from G1")
endif()
list(LENGTH _lmcp_sources _lmcp_source_count)
if(NOT _lmcp_source_count EQUAL 183)
    message(FATAL_ERROR "Expected all 183 library translation units for seven models")
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/lmcp-sources.txt" "${_lmcp_sources}\n")
