# Consumers must first call Resolve-LmcpCppPackage to verify live G1/T02 inputs.
get_filename_component(_lmcp_prefix "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(NOT EXISTS "${_lmcp_prefix}/build-info.json")
    message(FATAL_ERROR "LMCP package has no provenance")
endif()
file(READ "${_lmcp_prefix}/build-info.json" _lmcp_package)
string(JSON _lmcp_status GET "${_lmcp_package}" status)
if(NOT _lmcp_status STREQUAL "passed" AND NOT UXAS_LMCP_VALIDATE_CANDIDATE)
    message(FATAL_ERROR "LMCP package has not passed acceptance")
endif()
string(JSON _n LENGTH "${_lmcp_package}" files)
math(EXPR _last "${_n} - 1")
foreach(_i RANGE ${_last})
    string(JSON _p GET "${_lmcp_package}" files ${_i} path)
    string(JSON _h GET "${_lmcp_package}" files ${_i} sha256)
    if(NOT EXISTS "${_lmcp_prefix}/${_p}")
        message(FATAL_ERROR "LMCP package file missing: ${_p}")
    endif()
    file(SHA256 "${_lmcp_prefix}/${_p}" _actual)
    string(TOUPPER "${_actual}" _actual)
    if(NOT _actual STREQUAL _h)
        message(FATAL_ERROR "LMCP package file hash mismatch: ${_p}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/UxasLmcpTargets.cmake")
