import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const [project,output]=process.argv.slice(2);
const {footprint,validateSnapshot,areaRuns}=await import(pathToFileURL(resolve(project,'coverage-unit/coverage/geometry.js')));
const geoid=JSON.parse(readFileSync(resolve(project,'public/entities/runtime.json'))).height;
const ground=JSON.parse(readFileSync(resolve(project,'public/missions/runtime.json'))).ground;
const data=readFileSync(resolve(project,'public/missions/orthometric.f32'));
const heights={geoid,ground,values:new Float32Array(data.buffer,data.byteOffset,data.byteLength/4)};
const p=(lon,lat)=>({Longitude:lon,Latitude:lat,Altitude:0,AltitudeType:1});
const ordinary=[p(-121,45.2),p(-120.9,45.2),p(-120.9,45.3),p(-121,45.3)];
const f=footprint(ordinary,heights);assert.equal(f.clipped,false);assert.deepEqual(f.points,ordinary.map(p=>[p.Longitude,p.Latitude]));
assert.equal(footprint([],heights).points.length,0);
const clipped=footprint([p(-123,44),p(-119,44),p(-119,47),p(-123,47)],heights);assert.equal(clipped.clipped,true);assert.equal(clipped.points.length,4);
assert.ok(clipped.points.every(p=>p[0]>=-122&&p[0]<-120&&p[1]>=45&&p[1]<46));
assert.throws(()=>footprint([p(NaN,45),...ordinary],heights));
const task={taskId:'9223372036854775807',kind:'AreaSearchTask',cells:[[45.3,-121,0,0],[45.2998,-121,0,1],[45.2996,-121,0,2]],seen:[0,2],totalCells:3,seenCells:2,grid:{west:-121.0001,north:45.3001,dx:.0002,dy:.0002,columns:1,rows:3},contributors:['400'],observationMilliseconds:'0'};
assert.equal(areaRuns(task).length,2);task.seen=[0,1,2];task.seenCells=3;assert.equal(areaRuns(task).length,1);
const snapshot={schemaVersion:1,status:'live',runId:'run',cursor:['1','9007199254740993'],simulationTimeMs:'9007199254740993',gridResolutionMeters:20,sampledStates:1,tasks:[task]};
validateSnapshot(snapshot,'run');assert.throws(()=>validateSnapshot(snapshot,'other'));
assert.throws(()=>validateSnapshot({...snapshot,gridResolutionMeters:40},'run'));
assert.throws(()=>validateSnapshot({...snapshot,tasks:[{...task,seen:[100]}]},'run'));
writeFileSync(output,JSON.stringify({status:'passed',checks:['native planar corners ignore zero altitude','empty footprint','display clipping only','nonfinite refusal','noncontiguous seen cells not merged','contiguous cells merge for display only','large IDs','cross-run refusal','20m contract','invalid cell refusal']},null,2));
